create table TRANSMISSIONS
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO TRANSMISSIONS (name) VALUES ('Automatic');
GO
INSERT INTO TRANSMISSIONS (name) VALUES ('Mechanical');