create table TRANSMISSIONS
(
    id   bigint generated by default as identity (start with 1),
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO TRANSMISSIONS (name) VALUES ('Automatic');
GO
INSERT INTO TRANSMISSIONS (name) VALUES ('Mechanical');