create table RUDDERS
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO RUDDERS (name) VALUES ('Left');
GO
INSERT INTO RUDDERS (name) VALUES ('Right');