create table BRANDS
(
    id   bigint generated by default as identity (start with 1),
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO BRANDS (name) VALUES ('Audi');
GO
INSERT INTO BRANDS (name) VALUES ('BMW');
GO
INSERT INTO BRANDS (name) VALUES ('Ford');
GO
INSERT INTO BRANDS (name) VALUES ('Honda');
GO
INSERT INTO BRANDS (name) VALUES ('Hyundai');
GO
INSERT INTO BRANDS (name) VALUES ('Lada');
GO
INSERT INTO BRANDS (name) VALUES ('Mercedes-Benz');
GO
INSERT INTO BRANDS (name) VALUES ('Nissan');
GO
INSERT INTO BRANDS (name) VALUES ('Porsche');
GO
INSERT INTO BRANDS (name) VALUES ('Volvo');