create table ENGINES
(
    id   bigint generated by default as identity,
    type varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO ENGINES (type) VALUES ('Gasoline');
GO
INSERT INTO ENGINES (type) VALUES ('Diesel');
GO
INSERT INTO ENGINES (type) VALUES ('Electric');