create table BODIES
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO BODIES (name) VALUES ('Sedan');
GO
INSERT INTO BODIES (name) VALUES ('Universal');
GO
INSERT INTO BODIES (name) VALUES ('SUV');
GO
INSERT INTO BODIES (name) VALUES ('Crossover');
GO
INSERT INTO BODIES (name) VALUES ('Minibus');