create table MODELS
(
    id       bigint generated by default as identity (start with 1),
    name     varchar(255) not null,
    brand_id bigint,
    primary key (id)
);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('A4', 1);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('X5', 2);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Focus', 3);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Accord', 4);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Solaris', 5);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Vesta', 6);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('E', 7);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Leaf', 8);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('Taycan',9);
GO
INSERT INTO MODELS (name, brand_id) VALUES ('XC90',10);