create table RUDDERS
(
    id   bigint generated by default as identity (start with 1),
    name varchar(255) not null,
    primary key (id)
);
GO
INSERT INTO RUDDERS (name) VALUES ('Left');
GO
INSERT INTO RUDDERS (name) VALUES ('Right');